### ISSUE TITLE
Error: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ckeeney** [Ariel-Rodriguez/react-hook-sticky#10]
When trying to use this in a nextjs project, merely importing this library causes an error:

```
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.react-hook-sticky (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:7511:18)
    at __webpack_require__ (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:23:31)
    at Module../src/components/layout/index.js (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:5407:75)
    at __webpack_require__ (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:23:31)
    at Module../src/views/home.js (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:7216:76)
    at __webpack_require__ (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:23:31)
    at Module../src/pages/index.js (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:7104:69)
    at __webpack_require__ (/home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:23:31)
    at /home/ckeeney/src/gitlab.com/thenvindy/wp-frontend/.next/server/pages/index.js:91:18

```

![image](https://user-images.githubusercontent.com/8799010/118329406-d1ff8500-b4bb-11eb-8850-0e6918403022.png)

```
react-hook-sticky@^0.3.2:
  version "0.3.2"
  resolved "https://registry.yarnpkg.com/react-hook-sticky/-/react-hook-sticky-0.3.2.tgz#50fd708b76c111eac48aa39723e82153a93425ee"
  integrity sha512-O6Uq+6TQNiafG7kJl2ps/R6DNW4oso5mon950VvvWtxOszM1Bp2sg/XXOcpDRGZ68CKMfiaf0OOhAQtG9Uda7A==
```

**Comment by Ariel-Rodriguez** [comment]
hey @ckeeney --  This library is using the latest [ECMAS module definition](https://tc39.es/ecma262/#sec-modules). Your stack must transpile this library into your desired convention.

In your case, i recommend to transpile this module using this excellent plugin for NextJS
https://www.npmjs.com/package/next-transpile-modules


```
yarn add next-transpile-modules
```
```
// next.config.js
const withTM = require("next-transpile-modules")(["react-hook-sticky"]);
module.exports = withTM();
```
